--------------------------------------------------------
--  File created - Wednesday-September-25-2019   
--------------------------------------------------------
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\ACC_INT_DATA_ARR_REC_TYPE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\ACC_INT_DATA_REC_TYPE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\BAL_DAYS_REC_ARRAY_TYPE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\BAL_DAYS_REC_TYPE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_COL_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_COL_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_GSBA_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_GSBA_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_KEY_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_KEY_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_SEQ_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_SEQ_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_TAB_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_TAB_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_USER_GG_REC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TYPES\LOGMNR_USER_GG_RECS.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\LOGMNR_DIDS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\LOGMNR_EVOLVE_SEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\LOGMNR_SEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\LOGMNR_UIDS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\MVIEW__ADVSEQ_GENERIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\MVIEW__ADVSEQ_ID.sql
@C:\Users\hirak_patel\Desktop\bank_db\SEQUENCES\ROLLING_EVENT_SEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ACCOUNT_HISTORY.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ALL_CANDIDATES_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ALL_CANDIDATES_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__INTERNET_AGENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__INTERNET_AGENT_PRIVS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__KEY_SHARD_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__QUEUES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__QUEUE_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\AQ__SCHEDULES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\BANK_ACCOUNTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\BRANCH_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\CANDIDATE_SEGREGATION_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\CANDIDATE_SEGREGATION_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\CUSTOMERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\DEBIT_CARD_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\HELP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_CONCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_CON_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_DBNAME_UID_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_GSBA.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_GSII.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_INDCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_IND_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_SEQ_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRC_TSPART.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRGGC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRGGC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRP_CTAS_PART_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNRT_MDDL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_AGE_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_ATTRCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_ATTRIBUTE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_CCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_COLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_CON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_CONTAINER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_DICTIONARY_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_DICTSTATE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_DID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_ENC_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_ERROR_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_FILTER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_GLOBAL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_GT_TAB_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_GT_USER_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_GT_XID_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_ICOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_IDNSEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_IND_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_INDCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_INDPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_INDSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_KOPM_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_LOB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_LOBFRAG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_LOGMNR_BUILDLOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_NTAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_OPQTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PARAMETER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PARTOBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PDB_INFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PROCESSED_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PROFILE_PLSQL_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PROFILE_TABLE_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_PROPS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_REFCON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_RESTART_CKPT_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_RESTART_CKPT_TXINFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SEED_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SESSION_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SESSION_ACTIONS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SESSION_EVOLVE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_SUBCOLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TABCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TABPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TABSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_TYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_UID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGMNR_USER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_APPLY_MILESTONE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_APPLY_PROGRESS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_EDS_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_EVENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_FLASHBACK_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_HISTORY.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_PLSQL.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_SKIP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_SKIP_SUPPORT.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\LOGSTDBY_SKIP_TRANSACTION.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MONTH_DAY_LOOKUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_AJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_BASETABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_CLIQUE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_ELIGIBLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_EXCEPTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_FILTER.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_FILTERINSTANCE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_FJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_GC.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_INFO.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_JOURNAL.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_LEVEL.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_OUTPUT.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_PLAN.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_PRETTY.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_ROLLUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_SQLDEPEND.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\MVIEW__ADV_WORKLOAD.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\OL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\OL_HINTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\OL_NODES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\PROC_DT_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\REDO_DB.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\REDO_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_CONNECTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_DATABASES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_DIRECTIVES.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_EVENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_PLAN.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_STATISTICS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\ROLLING_STATUS.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\SCHEDULER_JOB_ARGS_TBL.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\SCHEDULER_PROGRAM_ARGS_TBL.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\SQLPLUS_PRODUCT_PROFILE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\TEMPTABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\TABLES\TRANSACTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\ALL_CANDIDATES_INFO_VW.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\CANDIDATES_INFO_450_VW.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MONTH_DAY_LKP_VW.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_EVALUATIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_EXCEPTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_FILTER.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_FILTERINSTANCE.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_RECOMMENDATIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\MVIEW_WORKLOAD.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\PRODUCT_PRIVS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\SCHEDULER_JOB_ARGS.sql
@C:\Users\hirak_patel\Desktop\bank_db\VIEWS\SCHEDULER_PROGRAM_ARGS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ACCOUNT_HISTORY.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ALL_CANDIDATES_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ALL_CANDIDATES_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__INTERNET_AGENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__INTERNET_AGENT_PRIVS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__KEY_SHARD_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__QUEUES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__QUEUE_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\AQ__SCHEDULES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\BANK_ACCOUNTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\BRANCH_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\CANDIDATE_SEGREGATION_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\CANDIDATE_SEGREGATION_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\CUSTOMERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\DEBIT_CARD_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\HELP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_CONCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_CON_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_DBNAME_UID_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_GSBA.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_GSII.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_INDCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_IND_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_SEQ_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRC_TSPART.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRGGC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRGGC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRP_CTAS_PART_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNRT_MDDL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_AGE_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_ATTRCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_ATTRIBUTE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_CCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_COLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_CON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_CONTAINER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_DICTIONARY_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_DICTSTATE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_DID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_ENC_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_ERROR_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_FILTER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_GLOBAL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_GT_TAB_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_GT_USER_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_GT_XID_INCLUDE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_ICOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_IDNSEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_IND_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_INDCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_INDPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_INDSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_KOPM_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_LOB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_LOBFRAG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_LOGMNR_BUILDLOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_NTAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_OPQTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PARAMETER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PARTOBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PDB_INFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PROCESSED_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PROFILE_PLSQL_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PROFILE_TABLE_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_PROPS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_REFCON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_RESTART_CKPT_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_RESTART_CKPT_TXINFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SEED_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SESSION_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SESSION_ACTIONS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SESSION_EVOLVE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_SUBCOLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TABCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TABPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TABSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_TYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_UID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGMNR_USER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_APPLY_MILESTONE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_APPLY_PROGRESS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_EDS_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_EVENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_FLASHBACK_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_HISTORY.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_PLSQL.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_SKIP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_SKIP_SUPPORT.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\LOGSTDBY_SKIP_TRANSACTION.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MONTH_DAY_LOOKUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_AJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_BASETABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_CLIQUE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_ELIGIBLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_EXCEPTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_FILTER.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_FILTERINSTANCE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_FJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_GC.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_INFO.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_JOURNAL.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_LEVEL.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_OUTPUT.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_PLAN.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_PRETTY.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_ROLLUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_SQLDEPEND.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\MVIEW__ADV_WORKLOAD.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\OL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\OL_HINTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\OL_NODES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\PROC_DT_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\REDO_DB.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\REDO_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_CONNECTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_DATABASES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_DIRECTIVES.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_EVENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_PLAN.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_STATISTICS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\ROLLING_STATUS.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\SCHEDULER_JOB_ARGS_TBL.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\SCHEDULER_PROGRAM_ARGS_TBL.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\SQLPLUS_PRODUCT_PROFILE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\TEMPTABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\DATA_TABLE\TRANSACTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRT_MDDL__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_AGE_SPILL__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_DID__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_PARAMETERS_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_ROLLUP_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_WORKLOAD_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\PK_BANK_ACCOUNTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\PK_BRANCH_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\PK_CUSTONERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\PK_DEBIT_CARD_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\PK_TRANSACTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\UNQ_PAIRS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_PDB_INFO__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_PROCESSED_LOG__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_PROFILE_PLSQL__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_PROFILE_TABLE__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_RESTART_CKPT__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_RESTART_CKPT_TXINFO__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_SESSION_ACTION__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_SESSION_EVOLVE__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_SESSION_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_SESSION_UK1.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_SPILL__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_UID__PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_EDS_TABLES_PKEY.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_AJG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_CLIQUE_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_ELIGIBLE_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_FILTER_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_FJG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_GC_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_INFO_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_JOURNAL_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_LEVEL_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_LOG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_OUTPUT_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_GSBA_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_GSII_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_GTCS_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_GTLO_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_INDCOL_GG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_IND_GG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_SEQ_GG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_SHARD_TS_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_TSPART_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_TS_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRGGC_GTCS_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRGGC_GTLO_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRP_CTAS_PART_MAP_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\HELP_TOPIC_SEQ.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_CONCOL_GG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_CON_GG_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_DBNAME_UID_MAP_PK.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1IDNSEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1INDCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1PROPS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1NTAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1ATTRCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1USER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1OPQTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2TABSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TABCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I2GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I2INDGG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\REDO_DB_IDX.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1INDSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_TEMP_IDX_01.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRP_CTAS_PART_MAP_I.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1INDPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_PARAMETER_INDX.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I1TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__FLAGS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I3COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1SUBCOLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1KOPM_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1LOB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2NTAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I3OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_PRETTY_IDX_01.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I1SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\REDO_LOG_IDX.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1CON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2IND_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_SQLDEPEND_IDX_01.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I1CONGG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2TABPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__PURGE_IDX2.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_SKIP_IND.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_EVENTS_IND_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1COLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRGGC_I2GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1CONTAINER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1ICOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__RECID.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1ENC_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I2GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\OL_NAME.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_EVENTS_IND_XID.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\I1_QUEUE_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2TAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TABPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\OL_HNT_NUM.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1ATTRIBUTE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1DICTIONARY_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\OL_SIGNATURE.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__FIRST_CHANGE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2USER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1CCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1IND_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I1TSPART.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2TABCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_LOG__PURGE_IDX1.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_SKIP_IDX2.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_WORKLOAD_IDX_01.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\I1_QUEUES.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1SEED_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2SEED_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I1INDGG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1PARTOBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRGGC_I3GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1LOGMNR_BUILDLOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I2CONGG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_EVENTS_IND.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I2SEQGG.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2INDPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\MVIEW__ADV_BASETABLE_IDX_01.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I3CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRGGC_I2GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1TABSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNRC_I3GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGSTDBY_SKIP_IDX1.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1LOBFRAG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I2IDNSEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\INDEXES\LOGMNR_I1REFCON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\PROCEDURES\CREDIT_DEBIT_OPERATION_SP.sql
@C:\Users\hirak_patel\Desktop\bank_db\PROCEDURES\DAILY_DATE_SET_SP.sql
@C:\Users\hirak_patel\Desktop\bank_db\PROCEDURES\INTEREST_CREDIT_SP.sql
@C:\Users\hirak_patel\Desktop\bank_db\PROCEDURES\PROCESS_TRANSACTION_SP.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_COL_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_GSBA_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_KEY_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_SEQ_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_TAB_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\FUNCTIONS\LOGMNR_USER_GG_TABF_PUBLIC.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\CATALOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\COL.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\PRODUCT_USER_PROFILE.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\PUBLICSYN.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\SYSCATALOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\SYSFILES.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\TAB.sql
@C:\Users\hirak_patel\Desktop\bank_db\SYNONYMS\TABQUOTAS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRGGC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_CONTAINER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_INFO.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_FILTER.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_IND_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PROPS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TABPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_CON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_GSBA.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_USER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_ROLLUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_LEVEL.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PROCESSED_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGSTDBY_SKIP_SUPPORT.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_LOB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PARAMETER_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGSTDBY_FLASHBACK_SCN.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_INDPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_ELIGIBLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_CLIQUE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_FJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\SQLPLUS_PRODUCT_PROFILE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_TSPART.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_AJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_INDCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PDB_INFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\BANK_ACCOUNTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_FILTERINSTANCE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_DICTIONARY_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGSTDBY_EDS_TABLES.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\DEBIT_CARD_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_COLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PROFILE_PLSQL_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_WORKLOAD.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SESSION_EVOLVE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRT_MDDL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_COL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\REDO_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_GSII.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_SEQ_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRGGC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SEED_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_DBNAME_UID_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_JOURNAL.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\TRANSACTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGSTDBY_EVENTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_LOBFRAG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PARTOBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_LOG_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_REFCON_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\CANDIDATE_SEGREGATION_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_AGE_SPILL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_ATTRCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_CCOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\ALL_CANDIDATES_TB_TEMP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_INDSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_BASETABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\HELP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_IDNSEQ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_IND_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_NTAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_GTCS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\REDO_DB.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_UID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_CONCOL_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TABSUBPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_OBJ_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SESSION_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRP_CTAS_PART_MAP.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_OUTPUT.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SHARD_TS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_LOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_GC.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TAB_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\BRANCH_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SESSION_ACTIONS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TABCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_SUBCOLTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGSTDBY_APPLY_MILESTONE.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_TYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_KOPM_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_CDEF_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_DID_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\CUSTOMERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_LOGMNR_BUILDLOG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\SCHEDULER_PROGRAM_ARGS_TBL.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\ALL_CANDIDATES_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_RESTART_CKPT_TXINFO_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_OPQTYPE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_INDCOMPART_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_DICTSTATE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\MVIEW__ADV_PARAMETERS.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\CANDIDATE_SEGREGATION_TB.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_GTLO.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_ATTRIBUTE_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_PROFILE_TABLE_STATS_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_ICOL_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_ENC_.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNRC_CON_GG.sql
@C:\Users\hirak_patel\Desktop\bank_db\CONSTRAINTS\LOGMNR_RESTART_CKPT_.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\BANK_ACCOUNTS.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\DEBIT_CARD_DETAILS.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_AJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_BASETABLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_CLIQUE.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_ELIGIBLE.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_EXCEPTIONS.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_FILTERINSTANCE.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_FJG.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_GC.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_INFO.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_JOURNAL.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_LEVEL.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_OUTPUT.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\MVIEW__ADV_ROLLUP.sql
@C:\Users\hirak_patel\Desktop\bank_db\REF_CONSTRAINTS\TRANSACTIONS.sql
