REM INSERTING into SYSTEM.BRANCH_DETAILS
SET DEFINE OFF;
Insert into SYSTEM.BRANCH_DETAILS (BRANCH_ID,BRANCH_NAME,BRANCH_ADDRESS,ISFC_CODE,CRTE_DT,CRTE_BY,MDFY_DT,MDFY_BY) values (101,'AMUL DAIRY ROAD','AMUL DAIRY ROAD, ANAND','ANAND001',to_date('13-SEP-19','DD-MON-RR'),'Manual Entry',null,null);
