REM INSERTING into SYSTEM.MONTH_DAY_LOOKUP
SET DEFINE OFF;
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('JAN',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('FEB',28);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('MAR',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('APR',30);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('MAY',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('JUN',30);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('JUL',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('AUG',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('SEP',30);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('OCT',31);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('NOV',30);
Insert into SYSTEM.MONTH_DAY_LOOKUP (MONTH_NAME,DAYS) values ('DEC',31);
