--------------------------------------------------------
--  Constraints for Table LOGMNRC_SHARD_TS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGMNRC_SHARD_TS" MODIFY ("LOGMNR_UID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRC_SHARD_TS" MODIFY ("TABLESPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRC_SHARD_TS" MODIFY ("CHUNK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRC_SHARD_TS" MODIFY ("START_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRC_SHARD_TS" ADD CONSTRAINT "LOGMNRC_SHARD_TS_PK" PRIMARY KEY ("LOGMNR_UID", "TABLESPACE_NAME", "START_SCN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  LOCAL
 (PARTITION "P_LESSTHAN100" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" )  ENABLE;
