--------------------------------------------------------
--  Constraints for Table LOGMNR_PDB_INFO$
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGMNR_PDB_INFO$" MODIFY ("LOGMNR_DID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_PDB_INFO$" MODIFY ("LOGMNR_MDH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_PDB_INFO$" MODIFY ("PLUGIN_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_PDB_INFO$" ADD CONSTRAINT "LOGMNR_PDB_INFO$_PK" PRIMARY KEY ("LOGMNR_DID", "LOGMNR_MDH", "PLUGIN_SCN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
