--------------------------------------------------------
--  Constraints for Table LOGMNRGGC_GTCS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("LOGMNR_UID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("OBJV#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("SEGCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("INTCOL#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("COLNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" MODIFY ("TYPE#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNRGGC_GTCS" ADD CONSTRAINT "LOGMNRGGC_GTCS_PK" PRIMARY KEY ("LOGMNR_UID", "OBJ#", "OBJV#", "INTCOL#")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
