--------------------------------------------------------
--  Constraints for Table LOGMNR_CONTAINER$
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("OBJ#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("CON_ID#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("CON_UID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("CREATE_SCNWRP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("CREATE_SCNBAS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_CONTAINER$" ADD CONSTRAINT "LOGMNR_CONTAINER$_PK" PRIMARY KEY ("LOGMNR_UID", "OBJ#") DISABLE;
