--------------------------------------------------------
--  Constraints for Table LOGMNR_SHARD_TS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGMNR_SHARD_TS" MODIFY ("LOGMNR_UID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_SHARD_TS" MODIFY ("TABLESPACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_SHARD_TS" MODIFY ("CHUNK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOGMNR_SHARD_TS" ADD CONSTRAINT "LOGMNR_SHARD_TS_PK" PRIMARY KEY ("LOGMNR_UID", "TABLESPACE_NAME") DISABLE;
