--------------------------------------------------------
--  Constraints for Table REDO_LOG
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("DBID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("THREAD#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("RESETLOGS_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("PRESETLOGS_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("SEQUENCE#" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("RESETLOGS_SCN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REDO_LOG" MODIFY ("PRESETLOGS_SCN" NOT NULL ENABLE);
