--------------------------------------------------------
--  DDL for Table BANK_ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BANK_ACCOUNTS" 
   (	"ACC_NO" NUMBER, 
	"CUST_ID" NUMBER, 
	"ACC_TYPE" VARCHAR2(50 BYTE), 
	"BRANCH_ID" NUMBER, 
	"IS_DEBIT_CARD_LINKED" VARCHAR2(1 BYTE), 
	"BALANCE" NUMBER, 
	"CRTE_DT" DATE, 
	"CRTE_BY" VARCHAR2(50 BYTE), 
	"MDFY_DT" TIMESTAMP (6), 
	"MDFY_BY" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_BANK_DATA" ;
