--------------------------------------------------------
--  DDL for Table LOGMNR_GT_TAB_INCLUDE$
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "SYSTEM"."LOGMNR_GT_TAB_INCLUDE$" SHARING=METADATA 
   (	"SCHEMA_NAME" VARCHAR2(390 BYTE), 
	"TABLE_NAME" VARCHAR2(390 BYTE), 
	"PDB_NAME" VARCHAR2(390 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000 BYTE)
   ) ON COMMIT PRESERVE ROWS ;
