--------------------------------------------------------
--  DDL for Table LOGMNR_PROFILE_PLSQL_STATS$
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOGMNR_PROFILE_PLSQL_STATS$" SHARING=METADATA 
   (	"PKGOWNER" VARCHAR2(384 BYTE), 
	"PKGNAME" VARCHAR2(384 BYTE), 
	"NAME" NUMBER, 
	"PRAGMAOP" NUMBER, 
	"OPNUM" NUMBER, 
	"TLSBYUNSUPPOPNUM" NUMBER, 
	"OGGUNSUPPOPNUM" NUMBER, 
	"REDOSIZE" NUMBER, 
	"REDORATE" NUMBER, 
	"SPARE1" VARCHAR2(384 BYTE), 
	"SPARE2" VARCHAR2(384 BYTE), 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER, 
	"SPARE5" NUMBER, 
	"SPARE6" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
