--------------------------------------------------------
--  DDL for Table ROLLING$PARAMETERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$PARAMETERS" SHARING=METADATA 
   (	"SCOPE" NUMBER, 
	"NAME" VARCHAR2(32 BYTE), 
	"ID" NUMBER, 
	"DESCRIP" VARCHAR2(256 BYTE), 
	"TYPE" NUMBER, 
	"DATATYPE" NUMBER, 
	"ATTRIBUTES" NUMBER, 
	"CURVAL" VARCHAR2(1024 BYTE), 
	"LSTVAL" VARCHAR2(1024 BYTE), 
	"DEFVAL" VARCHAR2(1024 BYTE), 
	"MINVAL" NUMBER, 
	"MAXVAL" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
