--------------------------------------------------------
--  DDL for Table ROLLING$STATUS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$STATUS" SHARING=METADATA 
   (	"REVISION" NUMBER, 
	"PHASE" NUMBER, 
	"BATCHID" NUMBER, 
	"STATUS" NUMBER, 
	"COORDID" NUMBER, 
	"OPRIMARY" NUMBER, 
	"FPRIMARY" NUMBER, 
	"PID" NUMBER, 
	"INSTANCE" NUMBER, 
	"DBTOTAL" NUMBER, 
	"DBACTIVE" NUMBER, 
	"LOCATION" VARCHAR2(128 BYTE), 
	"INIT_TIME" TIMESTAMP (6), 
	"BUILD_TIME" TIMESTAMP (6), 
	"START_TIME" TIMESTAMP (6), 
	"SWITCH_TIME" TIMESTAMP (6), 
	"FINISH_TIME" TIMESTAMP (6), 
	"LAST_INSTID" NUMBER, 
	"LAST_BATCHID" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
