--------------------------------------------------------
--  DDL for Table ROLLING$PLAN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$PLAN" SHARING=METADATA 
   (	"INSTID" NUMBER, 
	"BATCHID" NUMBER, 
	"DIRECTID" NUMBER, 
	"TASKID" NUMBER, 
	"REVISION" NUMBER, 
	"PHASE" NUMBER, 
	"STATUS" NUMBER, 
	"PROGRESS" NUMBER, 
	"SOURCE" NUMBER, 
	"TARGET" NUMBER, 
	"RFLAGS" NUMBER, 
	"OPCODE" NUMBER, 
	"P1" VARCHAR2(256 BYTE), 
	"P2" VARCHAR2(256 BYTE), 
	"P3" VARCHAR2(256 BYTE), 
	"P4" VARCHAR2(256 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"EXEC_STATUS" NUMBER, 
	"EXEC_INFO" VARCHAR2(256 BYTE), 
	"EXEC_TIME" TIMESTAMP (6), 
	"FINISH_TIME" TIMESTAMP (6), 
	"POST_STATUS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
