--------------------------------------------------------
--  DDL for Table ROLLING$DATABASES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$DATABASES" SHARING=METADATA 
   (	"RDBID" NUMBER, 
	"ATTRIBUTES" NUMBER, 
	"ATTRIBUTES2" NUMBER, 
	"DBUN" VARCHAR2(128 BYTE), 
	"DBID" NUMBER, 
	"PROD_RSCN" NUMBER, 
	"PROD_RID" NUMBER, 
	"PROD_SCN" NUMBER, 
	"CONS_RSCN" NUMBER, 
	"CONS_RID" NUMBER, 
	"CONS_SCN" NUMBER, 
	"ENGINE_STATUS" NUMBER, 
	"VERSION" VARCHAR2(128 BYTE), 
	"REDO_SOURCE" NUMBER, 
	"UPDATE_TIME" TIMESTAMP (6), 
	"REVISION" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
