--------------------------------------------------------
--  DDL for Table ROLLING$DIRECTIVES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$DIRECTIVES" SHARING=METADATA 
   (	"DIRECTID" NUMBER, 
	"PHASE" NUMBER, 
	"TASKID" NUMBER, 
	"FEATURE" VARCHAR2(32 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"TARGET" NUMBER, 
	"FLAGS" VARCHAR2(64 BYTE), 
	"OPCODE" NUMBER, 
	"P1" VARCHAR2(256 BYTE), 
	"P2" VARCHAR2(256 BYTE), 
	"P3" VARCHAR2(256 BYTE), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
