--------------------------------------------------------
--  DDL for Table ROLLING$CONNECTIONS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ROLLING$CONNECTIONS" SHARING=METADATA 
   (	"SOURCE_RDBID" NUMBER, 
	"DEST_RDBID" NUMBER, 
	"ATTRIBUTES" NUMBER, 
	"SERVICE_NAME" VARCHAR2(256 BYTE), 
	"CONN_HANDLE" NUMBER, 
	"CONNECT_TIME" TIMESTAMP (6), 
	"SEND_TIME" TIMESTAMP (6), 
	"DISCONNECT_TIME" TIMESTAMP (6), 
	"UPDATE_TIME" TIMESTAMP (6), 
	"SOURCE_PID" NUMBER, 
	"DEST_PID" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
